export const colombianCities = [
  { value: "yumbo", label: "Yumbo, Valle del Cauca" },
  { value: 'leticia', label: 'Leticia, Amazonas' },
  { value: 'medellin', label: 'Medellín, Antioquia' },
  { value: 'arauca', label: 'Arauca, Arauca' },
  { value: 'barranquilla', label: 'Barranquilla, Atlántico' },
  { value: 'bogota', label: 'Bogotá, D.C.' },
  { value: 'cartagena', label: 'Cartagena, Bolívar' },
  { value: 'tunja', label: 'Tunja, Boyacá' },
  { value: 'manizales', label: 'Manizales, Caldas' },
  { value: 'florencia', label: 'Florencia, Caquetá' },
  { value: 'yopal', label: 'Yopal, Casanare' },
  { value: 'popayan', label: 'Popayán, Cauca' },
  { value: 'valledupar', label: 'Valledupar, Cesar' },
  { value: 'quibdo', label: 'Quibdó, Chocó' },
  { value: 'monteria', label: 'Montería, Córdoba' },
  { value: 'bogota', label: 'Bogotá, Cundinamarca' },
  { value: 'riohacha', label: 'Riohacha, La Guajira' },
  { value: 'neiva', label: 'Neiva, Huila' },
  { value: 'santamarta', label: 'Santa Marta, Magdalena' },
  { value: 'villavicencio', label: 'Villavicencio, Meta' },
  { value: 'pasto', label: 'Pasto, Nariño' },
  { value: 'cucuta', label: 'Cúcuta, Norte de Santander' },
  { value: 'mocoa', label: 'Mocoa, Putumayo' },
  { value: 'armenia', label: 'Armenia, Quindío' },
  { value: 'pereira', label: 'Pereira, Risaralda' },
  { value: 'sanandres', label: 'San Andrés, San Andrés y Providencia' },
  { value: 'bucaramanga', label: 'Bucaramanga, Santander' },
  { value: 'sincelejo', label: 'Sincelejo, Sucre' },
  { value: 'ibague', label: 'Ibagué, Tolima' },
  { value: 'cali', label: 'Cali, Valle del Cauca' },
  { value: 'mitu', label: 'Mitú, Vaupés' },
  { value: 'puertocarreno', label: 'Puerto Carreño, Vichada' },
  // Ciudades adicionales importantes
  { value: 'palmira', label: 'Palmira, Valle del Cauca' },
  { value: 'bello', label: 'Bello, Antioquia' },
  { value: 'soledad', label: 'Soledad, Atlántico' },
  { value: 'envigado', label: 'Envigado, Antioquia' },
  { value: 'itagui', label: 'Itagüí, Antioquia' },
  { value: 'barrancabermeja', label: 'Barrancabermeja, Santander' },
  { value: 'zipaquira', label: 'Zipaquirá, Cundinamarca' },
  { value: 'facatativa', label: 'Facatativá, Cundinamarca' },
  { value: 'girardot', label: 'Girardot, Cundinamarca' },
  { value: 'dosquebradas', label: 'Dosquebradas, Risaralda' },
  { value: 'tulua', label: 'Tuluá, Valle del Cauca' },
  { value: 'barbosa', label: 'Barbosa, Antioquia' },
  { value: 'rionegro', label: 'Rionegro, Antioquia' },
  { value: 'giron', label: 'Girón, Santander' },
  { value: 'magangue', label: 'Magangué, Bolívar' },
  { value: 'maicao', label: 'Maicao, La Guajira' },
  { value: 'caucasia', label: 'Caucasia, Antioquia' },
  { value: 'turbo', label: 'Turbo, Antioquia' },
  { value: 'sabanalarga', label: 'Sabanalarga, Atlántico' },
  { value: 'malambo', label: 'Malambo, Atlántico' }
];